### ISSUE TITLE
Copy not implemented on types without `std` feature

### ISSUE THREAD

**Issue by vadixidav** [dimforge/nalgebra#774]
In `nalgebra 0.22.0`, `IsometryMatrix3<f64>` no longer implements `Copy` only when the `std` feature is not present. When it is present, `Copy` is implemented. This has created a downstream issue in Rust CV `cv-core`.

Here is a minimal test case:

```toml
[dependencies]
nalgebra = { version = "0.22.0", default-features = false }
```

```rust
use nalgebra::IsometryMatrix3;

#[derive(Debug, Clone, Copy)]
struct A(pub IsometryMatrix3<f64>);

fn main() {}
```
